; Auto-generated. Do not edit!


(cl:in-package mi_accion-msg)


;//! \htmlinclude ejFibonacciFeedback.msg.html

(cl:defclass <ejFibonacciFeedback> (roslisp-msg-protocol:ros-message)
  ((progreso
    :reader progreso
    :initarg :progreso
    :type cl:float
    :initform 0.0))
)

(cl:defclass ejFibonacciFeedback (<ejFibonacciFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ejFibonacciFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ejFibonacciFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mi_accion-msg:<ejFibonacciFeedback> is deprecated: use mi_accion-msg:ejFibonacciFeedback instead.")))

(cl:ensure-generic-function 'progreso-val :lambda-list '(m))
(cl:defmethod progreso-val ((m <ejFibonacciFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mi_accion-msg:progreso-val is deprecated.  Use mi_accion-msg:progreso instead.")
  (progreso m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ejFibonacciFeedback>) ostream)
  "Serializes a message object of type '<ejFibonacciFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'progreso))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ejFibonacciFeedback>) istream)
  "Deserializes a message object of type '<ejFibonacciFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progreso) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ejFibonacciFeedback>)))
  "Returns string type for a message object of type '<ejFibonacciFeedback>"
  "mi_accion/ejFibonacciFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ejFibonacciFeedback)))
  "Returns string type for a message object of type 'ejFibonacciFeedback"
  "mi_accion/ejFibonacciFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ejFibonacciFeedback>)))
  "Returns md5sum for a message object of type '<ejFibonacciFeedback>"
  "64f57b07fbcf153840824de661387d73")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ejFibonacciFeedback)))
  "Returns md5sum for a message object of type 'ejFibonacciFeedback"
  "64f57b07fbcf153840824de661387d73")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ejFibonacciFeedback>)))
  "Returns full string definition for message of type '<ejFibonacciFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float64 progreso~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ejFibonacciFeedback)))
  "Returns full string definition for message of type 'ejFibonacciFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float64 progreso~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ejFibonacciFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ejFibonacciFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ejFibonacciFeedback
    (cl:cons ':progreso (progreso msg))
))
