; Auto-generated. Do not edit!


(cl:in-package mi_accion-msg)


;//! \htmlinclude FibonacciResult.msg.html

(cl:defclass <FibonacciResult> (roslisp-msg-protocol:ros-message)
  ((secuencia_final
    :reader secuencia_final
    :initarg :secuencia_final
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass FibonacciResult (<FibonacciResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FibonacciResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FibonacciResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mi_accion-msg:<FibonacciResult> is deprecated: use mi_accion-msg:FibonacciResult instead.")))

(cl:ensure-generic-function 'secuencia_final-val :lambda-list '(m))
(cl:defmethod secuencia_final-val ((m <FibonacciResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mi_accion-msg:secuencia_final-val is deprecated.  Use mi_accion-msg:secuencia_final instead.")
  (secuencia_final m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FibonacciResult>) ostream)
  "Serializes a message object of type '<FibonacciResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'secuencia_final))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'secuencia_final))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FibonacciResult>) istream)
  "Deserializes a message object of type '<FibonacciResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'secuencia_final) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'secuencia_final)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FibonacciResult>)))
  "Returns string type for a message object of type '<FibonacciResult>"
  "mi_accion/FibonacciResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FibonacciResult)))
  "Returns string type for a message object of type 'FibonacciResult"
  "mi_accion/FibonacciResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FibonacciResult>)))
  "Returns md5sum for a message object of type '<FibonacciResult>"
  "f57464dd0bc7548f31a5a26b6588625f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FibonacciResult)))
  "Returns md5sum for a message object of type 'FibonacciResult"
  "f57464dd0bc7548f31a5a26b6588625f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FibonacciResult>)))
  "Returns full string definition for message of type '<FibonacciResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32[] secuencia_final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FibonacciResult)))
  "Returns full string definition for message of type 'FibonacciResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32[] secuencia_final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FibonacciResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'secuencia_final) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FibonacciResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FibonacciResult
    (cl:cons ':secuencia_final (secuencia_final msg))
))
