// Generated by gencpp from file mi_accion/ejFibonacciActionGoal.msg
// DO NOT EDIT!


#ifndef MI_ACCION_MESSAGE_EJFIBONACCIACTIONGOAL_H
#define MI_ACCION_MESSAGE_EJFIBONACCIACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <mi_accion/ejFibonacciGoal.h>

namespace mi_accion
{
template <class ContainerAllocator>
struct ejFibonacciActionGoal_
{
  typedef ejFibonacciActionGoal_<ContainerAllocator> Type;

  ejFibonacciActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ejFibonacciActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::mi_accion::ejFibonacciGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ejFibonacciActionGoal_

typedef ::mi_accion::ejFibonacciActionGoal_<std::allocator<void> > ejFibonacciActionGoal;

typedef boost::shared_ptr< ::mi_accion::ejFibonacciActionGoal > ejFibonacciActionGoalPtr;
typedef boost::shared_ptr< ::mi_accion::ejFibonacciActionGoal const> ejFibonacciActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator1> & lhs, const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator1> & lhs, const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mi_accion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1208bd9cabe660ab64b353d0439da9e9";
  }

  static const char* value(const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1208bd9cabe660abULL;
  static const uint64_t static_value2 = 0x64b353d0439da9e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mi_accion/ejFibonacciActionGoal";
  }

  static const char* value(const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ejFibonacciGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mi_accion/ejFibonacciGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 orden\n"
"\n"
;
  }

  static const char* value(const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ejFibonacciActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mi_accion::ejFibonacciActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::mi_accion::ejFibonacciGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MI_ACCION_MESSAGE_EJFIBONACCIACTIONGOAL_H
