// Generated by gencpp from file mi_accion/ejFibonacciFeedback.msg
// DO NOT EDIT!


#ifndef MI_ACCION_MESSAGE_EJFIBONACCIFEEDBACK_H
#define MI_ACCION_MESSAGE_EJFIBONACCIFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mi_accion
{
template <class ContainerAllocator>
struct ejFibonacciFeedback_
{
  typedef ejFibonacciFeedback_<ContainerAllocator> Type;

  ejFibonacciFeedback_()
    : progreso(0.0)  {
    }
  ejFibonacciFeedback_(const ContainerAllocator& _alloc)
    : progreso(0.0)  {
  (void)_alloc;
    }



   typedef double _progreso_type;
  _progreso_type progreso;





  typedef boost::shared_ptr< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ejFibonacciFeedback_

typedef ::mi_accion::ejFibonacciFeedback_<std::allocator<void> > ejFibonacciFeedback;

typedef boost::shared_ptr< ::mi_accion::ejFibonacciFeedback > ejFibonacciFeedbackPtr;
typedef boost::shared_ptr< ::mi_accion::ejFibonacciFeedback const> ejFibonacciFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator1> & lhs, const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progreso == rhs.progreso;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator1> & lhs, const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mi_accion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64f57b07fbcf153840824de661387d73";
  }

  static const char* value(const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64f57b07fbcf1538ULL;
  static const uint64_t static_value2 = 0x40824de661387d73ULL;
};

template<class ContainerAllocator>
struct DataType< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mi_accion/ejFibonacciFeedback";
  }

  static const char* value(const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float64 progreso\n"
"\n"
;
  }

  static const char* value(const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progreso);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ejFibonacciFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mi_accion::ejFibonacciFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mi_accion::ejFibonacciFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progreso: ";
    Printer<double>::stream(s, indent + "  ", v.progreso);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MI_ACCION_MESSAGE_EJFIBONACCIFEEDBACK_H
