// Generated by gencpp from file mi_accion/FibonacciFeedback.msg
// DO NOT EDIT!


#ifndef MI_ACCION_MESSAGE_FIBONACCIFEEDBACK_H
#define MI_ACCION_MESSAGE_FIBONACCIFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mi_accion
{
template <class ContainerAllocator>
struct FibonacciFeedback_
{
  typedef FibonacciFeedback_<ContainerAllocator> Type;

  FibonacciFeedback_()
    : secuencia_actual()  {
    }
  FibonacciFeedback_(const ContainerAllocator& _alloc)
    : secuencia_actual(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _secuencia_actual_type;
  _secuencia_actual_type secuencia_actual;





  typedef boost::shared_ptr< ::mi_accion::FibonacciFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mi_accion::FibonacciFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FibonacciFeedback_

typedef ::mi_accion::FibonacciFeedback_<std::allocator<void> > FibonacciFeedback;

typedef boost::shared_ptr< ::mi_accion::FibonacciFeedback > FibonacciFeedbackPtr;
typedef boost::shared_ptr< ::mi_accion::FibonacciFeedback const> FibonacciFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mi_accion::FibonacciFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mi_accion::FibonacciFeedback_<ContainerAllocator1> & lhs, const ::mi_accion::FibonacciFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.secuencia_actual == rhs.secuencia_actual;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mi_accion::FibonacciFeedback_<ContainerAllocator1> & lhs, const ::mi_accion::FibonacciFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mi_accion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mi_accion::FibonacciFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::FibonacciFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::FibonacciFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45ba1fe6faa9dbeeb53e7cfc94979ff6";
  }

  static const char* value(const ::mi_accion::FibonacciFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45ba1fe6faa9dbeeULL;
  static const uint64_t static_value2 = 0xb53e7cfc94979ff6ULL;
};

template<class ContainerAllocator>
struct DataType< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mi_accion/FibonacciFeedback";
  }

  static const char* value(const ::mi_accion::FibonacciFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32[] secuencia_actual\n"
"\n"
;
  }

  static const char* value(const ::mi_accion::FibonacciFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.secuencia_actual);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FibonacciFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mi_accion::FibonacciFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mi_accion::FibonacciFeedback_<ContainerAllocator>& v)
  {
    s << indent << "secuencia_actual[]" << std::endl;
    for (size_t i = 0; i < v.secuencia_actual.size(); ++i)
    {
      s << indent << "  secuencia_actual[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.secuencia_actual[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MI_ACCION_MESSAGE_FIBONACCIFEEDBACK_H
