// Generated by gencpp from file mi_accion/FibonacciGoal.msg
// DO NOT EDIT!


#ifndef MI_ACCION_MESSAGE_FIBONACCIGOAL_H
#define MI_ACCION_MESSAGE_FIBONACCIGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mi_accion
{
template <class ContainerAllocator>
struct FibonacciGoal_
{
  typedef FibonacciGoal_<ContainerAllocator> Type;

  FibonacciGoal_()
    : orden(0)  {
    }
  FibonacciGoal_(const ContainerAllocator& _alloc)
    : orden(0)  {
  (void)_alloc;
    }



   typedef int32_t _orden_type;
  _orden_type orden;





  typedef boost::shared_ptr< ::mi_accion::FibonacciGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mi_accion::FibonacciGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FibonacciGoal_

typedef ::mi_accion::FibonacciGoal_<std::allocator<void> > FibonacciGoal;

typedef boost::shared_ptr< ::mi_accion::FibonacciGoal > FibonacciGoalPtr;
typedef boost::shared_ptr< ::mi_accion::FibonacciGoal const> FibonacciGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mi_accion::FibonacciGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mi_accion::FibonacciGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mi_accion::FibonacciGoal_<ContainerAllocator1> & lhs, const ::mi_accion::FibonacciGoal_<ContainerAllocator2> & rhs)
{
  return lhs.orden == rhs.orden;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mi_accion::FibonacciGoal_<ContainerAllocator1> & lhs, const ::mi_accion::FibonacciGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mi_accion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mi_accion::FibonacciGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mi_accion::FibonacciGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mi_accion::FibonacciGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78b08bfea030c07bbabb797372e4dd97";
  }

  static const char* value(const ::mi_accion::FibonacciGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78b08bfea030c07bULL;
  static const uint64_t static_value2 = 0xbabb797372e4dd97ULL;
};

template<class ContainerAllocator>
struct DataType< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mi_accion/FibonacciGoal";
  }

  static const char* value(const ::mi_accion::FibonacciGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 orden\n"
;
  }

  static const char* value(const ::mi_accion::FibonacciGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orden);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FibonacciGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mi_accion::FibonacciGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mi_accion::FibonacciGoal_<ContainerAllocator>& v)
  {
    s << indent << "orden: ";
    Printer<int32_t>::stream(s, indent + "  ", v.orden);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MI_ACCION_MESSAGE_FIBONACCIGOAL_H
