// Generated by gencpp from file servicio_suma/AddTwoIntsRequest.msg
// DO NOT EDIT!


#ifndef SERVICIO_SUMA_MESSAGE_ADDTWOINTSREQUEST_H
#define SERVICIO_SUMA_MESSAGE_ADDTWOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servicio_suma
{
template <class ContainerAllocator>
struct AddTwoIntsRequest_
{
  typedef AddTwoIntsRequest_<ContainerAllocator> Type;

  AddTwoIntsRequest_()
    : a(0)
    , b(0)
    , c(0)
    , d(0)
    , e(0)  {
    }
  AddTwoIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , c(0)
    , d(0)
    , e(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;

   typedef int64_t _c_type;
  _c_type c;

   typedef int64_t _d_type;
  _d_type d;

   typedef int64_t _e_type;
  _e_type e;





  typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsRequest_

typedef ::servicio_suma::AddTwoIntsRequest_<std::allocator<void> > AddTwoIntsRequest;

typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsRequest > AddTwoIntsRequestPtr;
typedef boost::shared_ptr< ::servicio_suma::AddTwoIntsRequest const> AddTwoIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator1> & lhs, const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d &&
    lhs.e == rhs.e;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator1> & lhs, const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servicio_suma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5dbac4c99db764f8c94f70a3cdaf02d";
  }

  static const char* value(const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5dbac4c99db764fULL;
  static const uint64_t static_value2 = 0x8c94f70a3cdaf02dULL;
};

template<class ContainerAllocator>
struct DataType< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servicio_suma/AddTwoIntsRequest";
  }

  static const char* value(const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
"int64 c\n"
"int64 d\n"
"int64 e\n"
;
  }

  static const char* value(const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
      stream.next(m.e);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servicio_suma::AddTwoIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<int64_t>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<int64_t>::stream(s, indent + "  ", v.d);
    s << indent << "e: ";
    Printer<int64_t>::stream(s, indent + "  ", v.e);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICIO_SUMA_MESSAGE_ADDTWOINTSREQUEST_H
