// Auto-generated. Do not edit!

// (in-package mi_accion.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FibonacciResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.secuencia_final = null;
    }
    else {
      if (initObj.hasOwnProperty('secuencia_final')) {
        this.secuencia_final = initObj.secuencia_final
      }
      else {
        this.secuencia_final = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FibonacciResult
    // Serialize message field [secuencia_final]
    bufferOffset = _arraySerializer.int32(obj.secuencia_final, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FibonacciResult
    let len;
    let data = new FibonacciResult(null);
    // Deserialize message field [secuencia_final]
    data.secuencia_final = _arrayDeserializer.int32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.secuencia_final.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'mi_accion/FibonacciResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f57464dd0bc7548f31a5a26b6588625f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32[] secuencia_final
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FibonacciResult(null);
    if (msg.secuencia_final !== undefined) {
      resolved.secuencia_final = msg.secuencia_final;
    }
    else {
      resolved.secuencia_final = []
    }

    return resolved;
    }
};

module.exports = FibonacciResult;
