// Auto-generated. Do not edit!

// (in-package mi_accion.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FibonacciFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.secuencia_actual = null;
    }
    else {
      if (initObj.hasOwnProperty('secuencia_actual')) {
        this.secuencia_actual = initObj.secuencia_actual
      }
      else {
        this.secuencia_actual = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FibonacciFeedback
    // Serialize message field [secuencia_actual]
    bufferOffset = _arraySerializer.int32(obj.secuencia_actual, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FibonacciFeedback
    let len;
    let data = new FibonacciFeedback(null);
    // Deserialize message field [secuencia_actual]
    data.secuencia_actual = _arrayDeserializer.int32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.secuencia_actual.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'mi_accion/FibonacciFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '45ba1fe6faa9dbeeb53e7cfc94979ff6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32[] secuencia_actual
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FibonacciFeedback(null);
    if (msg.secuencia_actual !== undefined) {
      resolved.secuencia_actual = msg.secuencia_actual;
    }
    else {
      resolved.secuencia_actual = []
    }

    return resolved;
    }
};

module.exports = FibonacciFeedback;
